security:
    providers:
        in_memory:
            memory:
                users:
                    root:
                        password: $2y$13$mJLtvArzpxr/AeWhlPjSTeRqv8UIJuYpxO/3FH/n5DMAf8Bba8RKS
                        roles: 'ROLE_ADMIN'
                    admin:
                        password: $2y$13$DaMtG.IS6720tO8jvnhcy.4KpSdfOCpEkiSqWEIfa5IAf004cdydK
                        roles: 'ROLE_ADMIN'

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
            form_login:
                login_path: /admin/login
                check_path: /admin/login
            logout:
                path: /logout
                target: /

    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 13

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    access_control:
        - { path: ^/admin/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
